### ISSUE TITLE
Build failure with pyparsing version >2.4.7

### ISSUE THREAD

**Issue by dramthy** [revng/revng#124]
(Py3.revng) vscode ➜ ~/orchestra (master) $ orc install revng
[+] INFO - Executing Action install (build) of revng@optimized
[+] INFO - The following script is going to be executed:
cmake --build "$BUILD_DIR" ${JOBS:+-j$JOBS}
cmake --install "$BUILD_DIR"
if test "$RUN_TESTS" -eq 1; then
  cd "$BUILD_DIR"
  ctest --output-on-failure ${JOBS:+-j$JOBS}
  cd -
fi
[59/413] Generating DeadRegisterArgumentsOfFunction.h
FAILED: lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs/DeadRegisterArgumentsOfFunction.h 
cd /home/vscode/orchestra/build/revng/optimized/lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs && /home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py /home/vscode/orchestra/sources/revng/lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs/ABIAnalysis.template /home/vscode/orchestra/sources/revng/lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs/DeadRegisterArgumentsOfFunction.dot > DeadRegisterArgumentsOfFunction.h
Traceback (most recent call last):
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py", line 242, in <module>
    sys.exit(main())
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py", line 226, in main
    generated_code = process_graph(
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py", line 165, in process_graph
    _ = monotone_framework.check_lattice(lattice)
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework.py", line 109, in check_lattice
    assert bottom is None
AssertionError
[60/413] Generating DeadReturnValuesOfFunctionCall.h
FAILED: lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs/DeadReturnValuesOfFunctionCall.h 
cd /home/vscode/orchestra/build/revng/optimized/lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs && /home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py /home/vscode/orchestra/sources/revng/lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs/ABIAnalysis.template /home/vscode/orchestra/sources/revng/lib/EarlyFunctionAnalysis/ABIAnalyses/MFIGraphs/DeadReturnValuesOfFunctionCall.dot > DeadReturnValuesOfFunctionCall.h
Traceback (most recent call last):
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py", line 242, in <module>
    sys.exit(main())
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py", line 226, in main
    generated_code = process_graph(
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework_lattice.py", line 165, in process_graph
    _ = monotone_framework.check_lattice(lattice)
  File "/home/vscode/orchestra/sources/revng/scripts/monotone_framework.py", line 109, in check_lattice
    assert bottom is None
AssertionError
[67/413] Building CXX object CMakeFiles/test_pipeline.dir/tests/unit/Pipeline.cpp.o
[1/1] Running install (build) revng@optimized                                                                             

[74/413] Building CXX object lib/Model/CMakeFiles/revngModel.dir/SerializeModelPass.cpp.o
ninja: build stopped: subcommand failed.
[+] ERROR - Script failed with exit code 1

**Comment by aleclearmind** [comment]
It's a bug in `pyparsing`. We need to get in touch with upstream to fix this.
```
pip3 install --user pyparsing==2.4.7
```

**Comment by dramthy** [comment]
thanks @aleclearmind , it work for me. please claose it.

**Comment by aleclearmind** [comment]
We now explicitly check for `pyparsing` version at revng configure-time and provide a meaningful error message (f10bc1a410032d0ecb17d2c0947099d824a6da25).
