### ISSUE TITLE
Error “Assertion Error: assert to_extend_elf.elf.header.e_machine == source_elf.elf.header.e_machine” was reported  When using the "revng translate". 

### ISSUE THREAD

**Issue by ZaratustraN** [revng/revng#177]
I try to use translate function to translate a non-static binaries MIPS binary to a x86_64 binary, When i run `revng translate busybox busybox.translated`,  An error occuor when translate function using `/revng merge-dynamic /tmp/-0c3daa /tmp/-0bd188 /tmp/-cee805` to merge translated binary and the original one preserving information for the
dynamic loader from both binaries:  

```
Traceback (most recent call last):
  File "/revng/orchestra/build/revng/optimized/libexec/revng/revng-merge-dynamic", line 82, in <module>
    _main()
  File "/revng/orchestra/build/revng/optimized/libexec/revng/revng-merge-dynamic", line 77, in _main
    retcode = main()
  File "/revng/orchestra/build/revng/optimized/libexec/revng/revng-merge-dynamic", line 65, in main
    retcode = merge_dynamic(
  File "/revng/orchestra/build/revng/optimized/lib/python/revng/cli/merge_dynamic/merge_dynamic.py", line 75, in merge_dynamic
    assert to_extend_elf.elf.header.e_machine == source_elf.elf.header.e_machine
AssertionError
Check failed at  /revng/orchestra/sources/revng/lib/Recompile/LinkForTranslation.cpp:117

ExitCode == 0
```

 I notice this error occurs in the following code.

```c
   assert to_extend_elf.elf.header.e_machine == source_elf.elf.header.e_machine
```

but why `to_extend_elf` machine type must equal to `source_elf` mahine type, isn't the translation function used to translate programs  of different architectures?  

When I translate static binary everything works fine.

Here is the file where the error occurred: 
[busybox.zip](https://github.com/revng/revng/files/8684904/busybox.zip)

**Comment by aleclearmind** [comment]
Translation of non-static binaries is only supported for x86-64.

**Comment by ZaratustraN** [comment]
> Translation of non-static binaries is only supported for x86-64.

Thanks for answer！

**Comment by aleclearmind** [comment]
Proper solution for this is to implement `LinkForTranslation::checkPrecondition`: it should fail if `Architecture` is not x86-64 and the binary imports at least a dynamic library (best proxy we have for being a dynamic binary in the model).
