### ISSUE TITLE
`Model` parent directory not created

### ISSUE THREAD

**Issue by egberts** [revng/revng#370]
When executing `make`:

```
cd revng/build
cmake ..
make
```

Creating the `Model` subdirectory failed as in `revng/build/include/revng/Model/Generated`:

```
Traceback (most recent call last):
  File "/home/user/work/reverse-eng/revng/revng/scripts/tuple_tree_generator/tuple-tree-generate-cpp.py", line 70, in <module>
    main(parsed_args)
  File "/home/user/work/reverse-eng/revng/revng/scripts/tuple_tree_generator/tuple-tree-generate-cpp.py", line 64, in main
    full_output_path.parent.mkdir(exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/work/reverse-eng/revng/revng/build/include/revng/Model/Generated'
make[2]: *** [lib/Model/CMakeFiles/generate-revngModel-tuple-tree-code.dir/build.make:195: include/revng/Model/Generated/ForwardDecls.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:2589: lib/Model/CMakeFiles/generate-revngModel-tuple-tree-code.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Error is here (but not introduced by author as this is a new Python feature for `mkdir()`):

https://github.com/revng/revng/blame/cdfd91c3340459e19c0b0d6fb22ca145328bd178/scripts/tuple_tree_generator/tuple-tree-generate-cpp.py#L64

**Comment by egberts** [comment]
Workaround is to add `Parents=yes` option to `.mkdir()` in `tuple_tree_generator-cpp.py`

**Comment by egberts** [comment]
https://github.com/revng/revng/pull/371

**Comment by aleclearmind** [comment]
What Python version are you using?

**Comment by egberts** [comment]
Python 3.11

**Comment by aleclearmind** [comment]
We're using Python 3.11.8 🤔
I think you have some other issue. I'll look into it.

**Comment by aleclearmind** [comment]
Closing due to inactivity and failure to reproduce the problem.
